---
##########################
# netbox

{% raw -%}
netbox_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"
{%- endraw %}

{%- if cookiecutter.with_ceph|int %}
##########################
# cephclient

# FIXME: It does not work here to work with inventory groups because
#        because cephclient expects a list of IP addresses or hostnames
#        here that are not known when the configuration is created.
#
#        For cephclient_mons, a list of IP addresses or
#        hostnames must be set up on which the Ceph cluster can be
#        reached on the storage nodes.
cephclient_mons: []
{%- endif %}
