---
##########################
# k3s

apiserver_endpoint: 192.168.16.8
metal_lb_ip_range: "192.168.16.100-192.168.16.200"

##########################
# netbox

{% raw -%}
netbox_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"
{%- endraw %}
