---
##########################
# versions

{% if cookiecutter.with_ceph|int -%}
ceph_version: {{cookiecutter.ceph_version}}
{% endif -%}
manager_version: {{cookiecutter.manager_version}}
openstack_version: {{cookiecutter.openstack_version}}

##########################
# docker

docker_configure_repository: true

##########################
# operator

operator_user: dragon

##########################
# manager

{% if not cookiecutter.with_ceph|int -%}
ceph_ansible_enable: false
{% endif -%}

{% raw -%}
configure_cockpit: true
cockpit_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"

ara_enable: yes
ara_server_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"

awx_enable: no
awx_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"

awx_vault_type: vault
vault_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"

netbox_enable: no
netbox_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"
{%- endraw %}
