---
##########################
# versions

{% if cookiecutter.with_ceph|int -%}
ceph_version: {{cookiecutter.ceph_version}}
{% endif -%}
manager_version: {{cookiecutter.manager_version}}
openstack_version: {{cookiecutter.openstack_version}}

##########################
# docker

docker_configure_repository: true

##########################
# manager

{% if not cookiecutter.with_ceph|int -%}
ceph_ansible_enable: false
{% endif -%}

{% raw -%}
ara_enable: true
ara_server_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"

netbox_enable: true
netbox_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"

flower_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"
osism_api_host: "{{ hostvars[inventory_hostname]['ansible_' + console_interface]['ipv4']['address'] }}"
{%- endraw %}
