---
{%- if cookiecutter.with_ceph|int %}
##########################
# cephclient

cephclient_mons:
  - FIXME
{%- else %}
# Dummy variable to avoid error because ansible does not recognize the
# file as a good configuration file when no variable in it.
dummy:
{%- endif %}
