---
##########################
# netbox

{% raw -%}
netbox_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"
{%- endraw %}

{%- if cookiecutter.with_ceph|int %}
##########################
# cephclient

cephclient_mons:
  - FIXME
{%- endif %}
