---
##########################
# versions

{%- if cookiecutter.with_ceph|int %}
ceph_version: {{cookiecutter.ceph_version}}
{%- endif %}
openstack_version: {{cookiecutter.openstack_version}}
{%- if cookiecutter.with_ceph|int == 0 %}
##########################
# helper

configure_cephclient: no
{%- endif %}
{%- if cookiecutter.with_ceph|int %}

##########################
# cephclient

{% raw -%}
cephclient_mons:
  - FIXME
{%- endraw %}
{%- endif %}
