---
##########################
# configuration

configuration_directory: /opt/configuration
configuration_git_private_key_file: ~/.ssh/id_rsa.configuration
configuration_type: git

configuration_git_host: {{cookiecutter.git_host}}
configuration_git_port: {{cookiecutter.git_port}}
# yamllint disable rule:line-length
configuration_git_public_key: FIXME
# yamllint enable rule:line-length
configuration_git_protocol: ssh
configuration_git_repository: {{cookiecutter.git_repository}}
configuration_git_username: {{cookiecutter.git_username}}
configuration_git_version: {{cookiecutter.git_version}}

##########################
# docker

{% raw -%}
docker_user: "{{ operator_user }}"
{%- endraw %}

docker_configure_storage_driver: true
docker_storage_driver: overlay2

docker_configure_insecure_registries: true
docker_insecure_registries:
  - {{cookiecutter.docker_registry}}

{%- if cookiecutter.with_ceph|int %}
ceph_docker_registry: {{cookiecutter.docker_registry}}
{%- endif %}
docker_registry: index.docker.io
docker_registry_ansible: {{cookiecutter.docker_registry}}

##########################
# versions

docker_version: "{{cookiecutter.docker_version}}"
repository_version: {{cookiecutter.repository_version}}

##########################
# operator

operator_user: dragon

# yamllint disable rule:line-length
operator_public_key: FIXME
# yamllint enable rule:line-length

{% raw -%}
operator_authorized_keys:
  - "{{ operator_public_key }}"
{%- endraw %}

##########################
# resolvconf

resolvconf_nameserver:
{%- for name_server in cookiecutter.name_servers.get("values") %}
  - {{ name_server }}
{%- endfor %}
resolvconf_search: {{cookiecutter.domain}}
resolvconf_package: ""

##########################
# hosts

hosts_type: template
hosts_additional_entries:
  {{cookiecutter.fqdn_internal}}: {{cookiecutter.ip_internal}}
{%- if cookiecutter.fqdn_external != cookiecutter.fqdn_internal %}
  {{cookiecutter.fqdn_external}}: {{cookiecutter.ip_external}}
{%- endif %}

##########################
# common

cleanup_services_extra:
  - NetworkManager
  - iscsid
  - lxcfs
  - nscd
  - ntp

##########################
# proxy

proxy_package_manager: false
proxy_proxies: {}

##########################
# kolla

kolla_internal_vip_address: {{cookiecutter.ip_internal}}
{%- if cookiecutter.ip_external != cookiecutter.ip_internal %}
kolla_external_vip_address: {{cookiecutter.ip_external}}
{%- endif %}

##########################
# serial

osism_serial_default: 100%
osism_serial:
  docker: 1

##########################
# chrony

chrony_servers:
{%- for ntp_server in cookiecutter.ntp_servers.get("values") %}
  - {{ ntp_server }}
{%- endfor %}
chrony_allowed_subnets:
  - 127.0.0.1/32
{%- if cookiecutter.with_ceph|int %}

##########################
# ceph

ceph_share_directory: /share
ceph_cluster_fsid: {{cookiecutter.ceph_fsid}}
{%- endif %}
