---
##########################
# configuration

configuration_directory: /opt/configuration
configuration_git_private_key_file: ~/.ssh/id_rsa.configuration
configuration_type: git

configuration_git_host: {{cookiecutter.git_host}}
configuration_git_port: {{cookiecutter.git_port}}
# yamllint disable rule:line-length
configuration_git_public_key: FIXME
# yamllint enable rule:line-length
configuration_git_protocol: ssh
configuration_git_repository: {{cookiecutter.git_repository}}
configuration_git_username: {{cookiecutter.git_username}}
configuration_git_version: {{cookiecutter.git_version}}

##########################
# docker

{% raw -%}
docker_user: "{{ operator_user }}"
{%- endraw %}

docker_configure_repository: no

docker_configure_storage_driver: yes
docker_storage_driver: overlay2

docker_configure_insecure_registries: yes
docker_insecure_registries:
  - {{cookiecutter.docker_registry}}

{%- if cookiecutter.with_ceph|int %}
ceph_docker_registry: {{cookiecutter.docker_registry}}
{%- endif %}
docker_registry: {{cookiecutter.docker_registry}}

##########################
# versions

docker_version: "{{cookiecutter.docker_version}}"
repository_version: {{cookiecutter.repository_version}}

##########################
# operator

# yamllint disable rule:line-length
operator_public_key: FIXME
# yamllint enable rule:line-length

{% raw -%}
operator_authorized_keys:
  - "{{ operator_public_key }}"
{%- endraw %}

##########################
# proxy

proxy_proxies: {}

##########################
# resolvconf

resolvconf_nameserver:
{%- for name_server in cookiecutter.name_servers.get("values") %}
  - {{ name_server }}
{%- endfor %}
resolvconf_search: {{cookiecutter.domain}}
resolvconf_package: ""

##########################
# hosts

hosts_type: template
hosts_additional_entries:
  {{cookiecutter.fqdn_internal}}: {{cookiecutter.ip_internal}}
{%- if cookiecutter.fqdn_external != cookiecutter.fqdn_internal %}
  {{cookiecutter.fqdn_external}}: {{cookiecutter.ip_external}}
{%- endif %}

##########################
# common

cleanup_services_common:
  - NetworkManager
  - iscsid
  - lxcfs
  - nscd
  - ntp

install_microcode_package_common: yes
rng_enable_common: yes

##########################
# kolla

kolla_internal_vip_address: {{cookiecutter.ip_internal}}
{%- if cookiecutter.ip_external != cookiecutter.ip_internal %}
kolla_external_vip_address: {{cookiecutter.ip_external}}
{%- endif %}

##########################
# serial

osism_serial_default: 30%
osism_serial:
  chrony: 100%
  common: 100%
  docker: 1
  grub: 100%
  hardening: 100%
  hostname: 100%
  hosts: 100%
  operator: 100%
  pipelining: 100%
  proxy: 100%
  python: 100%
  repository: 100%
  resolvconf: 100%
  timezone: 100%
  utilities: 100%

##########################
# chrony

chrony_servers:
{%- for ntp_server in cookiecutter.ntp_servers.get("values") %}
  - {{ ntp_server }}
{%- endfor %}
chrony_allowed_subnets:
  - 127.0.0.1/32

##########################
# hardening

stig_version: rhel7

# NOTE: osism.chrony is used instead of this integration
security_rhel7_enable_chrony: no

# NOTE: http://docs.openstack.org/developer/kolla-ansible/security.html#selinux
security_rhel7_enable_linux_security_module: no

security_rhel7_remove_shosts_files: yes
security_package_clean_on_remove: yes

security_rhel7_session_timeout: 3600

# NOTE(berendt): allow hmac-sha1 to make cockpit usable
#                https://github.com/cockpit-project/cockpit/issues/8733
security_sshd_allowed_macs: hmac-sha2-256,hmac-sha2-512,hmac-sha1
{%- if cookiecutter.with_ceph|int %}

##########################
# ceph

ceph_share_directory: /share
ceph_cluster_fsid: {{cookiecutter.ceph_fsid}}
{%- endif %}
