---
{%- if cookiecutter.with_keycloak|int %}
# keycloak-oidc-client-config
{% raw -%}
keycloak_admin_id: "admin"
keycloak_key_provider_component_name: "rsa-for-keystone"

keystone_client_id: "keystone"
keystone_redirect_uris:
  - "https://{{ kolla_external_fqdn }}:5000/redirect_uri"
  - "https://{{ kolla_external_fqdn }}"
  - "https://{{ kolla_external_vip_address }}:5000/redirect_uri"
  - "https://{{ kolla_external_vip_address }}"

keycloak_private_key_file_path: "{{ configuration_directory }}/environments/custom/files/keycloak/private_key.pem"
keycloak_private_key_data: "{{ lookup('file', keycloak_private_key_file_path)| regex_replace('\n', '\\\\n') }}"

keycloak_certificate_file_path: "{{ configuration_directory }}/environments/custom/files/keycloak/cert.crt"
keycloak_certificate_data: "{{ lookup('file', keycloak_certificate_file_path)| regex_replace('\n', '\\\\n') }}"
{%- endraw %}
{%- else %}
# Dummy variable to avoid error because ansible does not recognize the
# file as a good configuration file when no variable in it.
dummy:
{%- endif %}
