---
- secret:
    name: SECRET_CFG_COOKIECUTTER
    data:
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - noosIQXkV09i7bYnr+8b9P14EPH/Pzpu0Ax0kJs4NhKLN8+s2wPnhZF+KVmuIJ6bjlBpY
          JENpWT8Dg7guTFYEky4aqBTQnukvQYSqpIDsi02hTJa+3z5IScjnNMIbzxIFaHb35dNhc
          kpuTPV7nf1AWe04WGPEo3gHT9gVla6L2dm6yQq/9jB12Fu4MXkJWyr8ZnSm1GtQI9lWDx
          1LcXdSu2hFYwPLM+DS0KmPLIDg7Q8VsRG3NaMfAxJLrONhj+p3qedGJMBNo9KE2or0w7n
          SJgt41w6/jkp8ttAAg/iOx2NgF3ztcyzebkRAEi5he4T+20sDCP7NByFl1HP6v2UMkvCJ
          ylSWd73dOOBTbbd6oW+GIp5sqNstNTooS6elsTYuNuhk//7kheoDrntLcce6qNw5G8pi9
          pCKJRFJyx72pEXF7UbIwtLv9AQwHEkwmZxp08XY65faS1w3jhZTlNzbOQg9sF/KVV9dZo
          xO3Kh66QUIII32EY0rkWu3gT4TOKQJ/x652X95E3uQSmyTS4EFYlPRIUTtgckeC/Iqsyo
          /t8ufLkMOY9iwR/0TbXl4shqUWdLCnyZi4EWDTA7PB93jWzbEvUtufJAA2bPz1zPnMeQ6
          NXlqBG3pqsmJNVqV2wznJq5VRo80Gq+1G0Qc+KcvQV3MIqbyn/qaCpheathNsw=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - MLFCvkzsxQ4ZtIdOGgBoTaH4PAx7nBAtadDwjP4JzK01hBJKRQDbrV1i+TI3WnFJYbw7B
          V1ft5eiKckNNyda44uioAnIW1S3+SAdHqpkfI8KYdSvXO27MHMrv7oqO3frW/UtxBmN8Z
          dkkY3Q6034vzxY2/csXae3PBysALxVN6H1plT188F5vAyIFyr++9Xbu11kzTYymCiDu3E
          y2d1vxPI+b4T9MNqcs2ZeKIfbETs/XlrgaOhGlv2aJ1eZ7uLFZ9XZJgzoYFjj3O4dFJ+L
          qq3aE1A8HqN4D0uEMtVQmsvQ4zHnkL2M568eD5K0VFGlxqQQovCkiLxB53eGKoefHHdac
          ve1m6/TWiZ+K5PzU1rM36rjV5g778xBmDIE4y9kSmakK23rKpMRkgYVT5BJ4n91vn8o3V
          1/di39KiNq5MxAqx5Ov4Iv3btNKv4jYTBs0RDgfL6n4AuYMXacEYDnJxI37J9HuPt6+Bx
          VcZ1dwDYxdpbnv2qNeqVxU77tqQc741LXKPe+9+8JNYoLEhzBoZ+Dk/AclYA0fRlpLzt1
          LCcGwwg4x/XJ5Hf+Jm7QBU21TEeNnOBqWiebQ4wukoivayHVx5ArzaICwsyW5944eXOVB
          AAadHBVr4GU1kBdCm1he/CupCyE4GX2DTLhOqYfkty4qn/R7Rgb9cCgAkIKxgM=

- semaphore:
    name: semaphore-container-image-cfg-cookiecutter-push
    max: 1

- job:
    name: container-image-cfg-cookiecutter-build
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital
      push_image: false

- job:
    name: container-image-cfg-cookiecutter-push
    semaphores:
      - name: semaphore-container-image-cfg-cookiecutter-push
    pre-run: playbooks/pre.yml
    run: playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital
      push_image: true
    secrets:
      - name: secret
        secret: SECRET_CFG_COOKIECUTTER

- job:
    name: cfg-cookiecutter-tox
    parent: tox
    vars:
      tox_envlist: cookiecutter

- job:
    name: cfg-cookiecutter-tox-2023.2
    parent: cfg-cookiecutter-tox
    vars:
      tox_environment:
        OPENSTACK_VERSION: "2023.2"

- job:
    name: cfg-cookiecutter-tox-2024.1
    parent: cfg-cookiecutter-tox
    vars:
      tox_environment:
        OPENSTACK_VERSION: "2024.1"

- job:
    name: cfg-cookiecutter-tox-2024.2
    parent: cfg-cookiecutter-tox
    vars:
      tox_environment:
        OPENSTACK_VERSION: "2024.2"

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
        - cfg-cookiecutter-tox-2023.2
        - cfg-cookiecutter-tox-2024.1
        - cfg-cookiecutter-tox-2024.2
        - container-image-cfg-cookiecutter-build
    gate:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
        - cfg-cookiecutter-tox-2023.2
        - cfg-cookiecutter-tox-2024.1
        - cfg-cookiecutter-tox-2024.2
    periodic-daily:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
        - cfg-cookiecutter-tox-2023.2
        - cfg-cookiecutter-tox-2024.1
        - cfg-cookiecutter-tox-2024.2
        - container-image-cfg-cookiecutter-push
    post:
      jobs:
        - container-image-cfg-cookiecutter-push:
            branches: main
