---
##########################################################
# ansible

ansible_host: 192.168.16.5

##########################################################
# generic

internal_interface: eno1

##########################################################
# network

# NOTE: This is the initial management interface. Further interfaces can be added.
# DOCS: https://osism.tech/docs/guides/configuration-guide/network
network_ethernets:
  eno1:
    addresses:
      - "192.168.16.10/20"
    gateway4: "192.168.16.1"
    mtu: 1500
