# NOTE: This file must be edited before using the configuration repository.
#       This file serves as a template for a manager node. It is sufficient
#       to only add the host vars of the manager node in the inventory of
#       the manager environment. The host vars of all other nodes belong in
#       the global inventory. The manager node must also be added in the
#       global inventory. The IP addresses, interface names etc. are examples.
#       This file (node01.yml) is removed and should not be present in the
#       configuration repository.
---
##########################################################
# ansible

# NOTE: Address where the node can be reached via SSH. If DHCP is used after the
#       initial provisioning to assign an IP address to the nodes, the address
#       assigned via DHCP is initially used here and later adapted to the static
#       IP address.
ansible_host: 192.168.16.10

##########################################################
# generic

internal_interface: eno1

##########################################################
# network

# NOTE: This is the initial management interface. Further interfaces can be added.
# DOCS: https://osism.tech/docs/guides/configuration-guide/network
network_ethernets:
  eno1:
    addresses:
      - "192.168.16.10/20"
    gateway4: "192.168.16.1"
    mtu: 1500
