---
##########################
# docker

{% raw -%}
docker_user: "{{ operator_user }}"
{%- endraw %}

##########################
# operator

operator_user: dragon

# yamllint disable rule:line-length
operator_public_key: FIXME
# yamllint enable rule:line-length

{% raw -%}
operator_authorized_keys:
  - "{{ operator_public_key }}"
{%- endraw %}

##########################
# resolvconf

resolvconf_nameserver:
  - {{cookiecutter.name_server}}
resolvconf_search: {{cookiecutter.domain}}

##########################
# hosts

hosts_type: local
hosts_additional_entries:
  {{cookiecutter.fqdn_internal}}: {{cookiecutter.ip_internal}}
{%- if cookiecutter.fqdn_external != cookiecutter.fqdn_internal %}
  {{cookiecutter.fqdn_external}}: {{cookiecutter.ip_external}}
{%- endif %}

##########################
# ansible

osism_serial_default: 100%
osism_serial:
  docker: 1

##########################
# chrony

chrony_servers:
  - {{cookiecutter.ntp_server}}
chrony_allowed_subnets:
  - 127.0.0.1/32
{%- if cookiecutter.with_ceph|int %}

##########################
# ceph

ceph_cluster_fsid:
{%- endif %}
