---
##########################
# docker

docker_version: "{{cookiecutter.docker_version}}"
{% raw -%}
docker_user: "{{ operator_user }}"
{%- endraw %}

##########################
# docker registries

{%- if cookiecutter.with_ceph|int %}
ceph_docker_registry: quay.io
{%- endif %}
docker_registry: index.docker.io
docker_registry_ansible: quay.io
docker_registry_service: index.docker.io

##########################
# operator

operator_user: dragon

# yamllint disable rule:line-length
operator_public_key: FIXME
# yamllint enable rule:line-length

{% raw -%}
operator_authorized_keys:
  - "{{ operator_public_key }}"
{%- endraw %}

##########################
# resolvconf

resolvconf_nameserver:
  - {{cookiecutter.name_server}}
resolvconf_search: {{cookiecutter.domain}}

##########################
# hosts

hosts_type: template
hosts_additional_entries:
  {{cookiecutter.fqdn_internal}}: {{cookiecutter.ip_internal}}
{%- if cookiecutter.fqdn_external != cookiecutter.fqdn_internal %}
  {{cookiecutter.fqdn_external}}: {{cookiecutter.ip_external}}
{%- endif %}

##########################
# kolla

kolla_internal_vip_address: {{cookiecutter.ip_internal}}
{%- if cookiecutter.ip_external != cookiecutter.ip_internal %}
kolla_external_vip_address: {{cookiecutter.ip_external}}
{%- endif %}

##########################
# serial

osism_serial_default: 100%
osism_serial:
  docker: 1

##########################
# chrony

chrony_servers:
  - {{cookiecutter.ntp_server}}
chrony_allowed_subnets:
  - 127.0.0.1/32
{%- if cookiecutter.with_ceph|int %}

##########################
# ceph

ceph_share_directory: /share
ceph_cluster_fsid: {{cookiecutter.ceph_fsid}}
{%- endif %}
