---
##########################################################
# ansible

ansible_host: 10.1.10.40

##########################################################
# generic

console_interface: vlan10
management_interface: vlan20

internal_address: 10.1.20.40
fluentd_host: 10.1.20.40

##########################################################
# cockpit

cockpit_ssh_interface: vlan10

##########################################################
# network-interfaces

network_allow_service_restart: false
network_restart_method: nothing

network_interfaces:
  - device: enp3s0f0
    auto: true
    family: inet
    method: manual
    bond:
      master: bond0
    mtu: 9000

  - device: enp3s0f1
    auto: true
    family: inet
    method: manual
    bond:
      master: bond0
    mtu: 9000

  - device: bond0
    auto: true
    family: inet
    method: manual
    bond:
      mode: 802.3ad
      xmit-hash-policy: layer3+4
      miimon: 100
      slaves: enp3s0f0 enp3s0f1
      lacp-rate: 1
    mtu: 9000

  - device: vlan10
    method: static
    address: 10.1.10.40
    netmask: 255.255.255.0
    gateway: 10.1.10.1
    vlan:
      raw-device: bond0
    mtu: 9000

  - device: vlan20
    method: static
    address: 10.1.20.40
    netmask: 255.255.255.0
    vlan:
      raw-device: bond0
    mtu: 9000

##########################################################
# kolla

network_interface: vlan20

##########################################################
# ceph

monitor_interface: vlan20
# monitor_address:
# radosgw_interface:
# radosgw_address:

devices:
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
