---
##########################
# patchman-client

patchman_client_host: "{{ '{{' }} hostvars['manager01.{{cookiecutter.domain}}']['ansible_' + hostvars['manager01.{{cookiecutter.domain}}']['management_interface']]['ipv4']['address'] {{ '}}' }}"
