---
##########################
# patchman-client

patchman_client_server_url: http://{{ '{{' }} hostvars['manager01.{{cookiecutter.domain}}']['ansible_' + management_interface]['ipv4']['address'] {{ '}}' }}:8150
