---
- name: Manage cronjobs on the manager node
  hosts: manager
  gather_facts: false

  tasks:
    - name: Run helper scripts non-interactive
      cron:
        name: INTERACTIVE
        env: true
        value: "false"
        cron_file: osism
{%- raw %}
        user: "{{ operator_user }}"{% endraw %}
      become: true

    - name: Gather facts
      cron:
        name: "gather facts"
        minute: "15"
        hour: "*/6"
        job: /usr/local/bin/osism-run-without-secrets generic facts
        cron_file: osism
{%- raw %}
        user: "{{ operator_user }}"{% endraw %}
      become: true

#    - name: Collect sosreports
#      cron:
#        name: "collect sosreport"
#        minute: "0"
#        hour: "4"
#        job: /usr/local/bin/osism-run-without-secrets generic sosreport
#        cron_file: osism
{%- raw %}
#        user: "{{ operator_user }}"{% endraw %}
#      become: true

#    - name: Cleanup docker images
#      cron:
#        name: "cleanup docker images"
#        minute: "0"
#        hour: "2"
#        job: /usr/local/bin/osism-run-without-secrets generic cleanup-docker --tags images
#        cron_file: osism
{%- raw %}
#        user: "{{ operator_user }}"{% endraw %}
#      become: true

#    - name: Delete old sosreport archives
#      cron:
#        name: "delete old sosreport archives"
#        minute: "15"
#        hour: "3"
#        job: /usr/local/bin/osism-run-without-secrets generic cleanup-sosreport
#        cron_file: osism
{%- raw %}
#        user: "{{ operator_user }}"{% endraw %}
#      become: true

#    - name: Upgrade packages
#      cron:
#        name: "upgrade packages"
#        minute: "5"
#        hour: "0"
#        job: /usr/local/bin/osism-run-without-secrets generic upgrade-packages
#        cron_file: osism
{%- raw %}
#        user: "{{ operator_user }}"{% endraw %}
#      become: true
