---
##########################
# docker registries

docker_registry: index.docker.io
docker_registry_ansible: quay.io
docker_registry_service: index.docker.io

##########################
# versions

{% if cookiecutter.with_ceph|int -%}
ceph_version: {{cookiecutter.ceph_version}}
{% endif -%}
manager_version: {{cookiecutter.manager_version}}
openstack_version: {{cookiecutter.openstack_version}}

{% if not cookiecutter.with_ceph|int -%}
##########################
# ansible

ceph_ansible_enable: false
{% endif -%}

##########################
# ara

{% raw -%}
ara_enable: true
ara_server_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"

##########################
# listener

# FIXME: It does not work here to work with inventory groups because
#        the manager's inventory is independent from the rest of the
#        inventory.
#
#        For manager_listener_broker_hosts, a list of IP addresses or
#        hostnames must be set up on which the RabbitMQ Broker can be
#        reached on the control nodes.

manager_listener_broker_hosts: []
manager_listener_broker_username: openstack
manager_listener_broker_uri: "{% for host in manager_listener_broker_hosts %}amqp://{{ manager_listener_broker_username }}:{{ manager_listener_broker_password }}@{{ host }}:5672/{% if not loop.last %};{% endif %}{% endfor %}"

##########################
# netbox

netbox_enable: true
netbox_api_url: "http://{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}:8121"

##########################
# celery

celery_enable: true
flower_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"
osism_api_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"
{%- endraw %}

##########################
# configuration

configuration_directory: /opt/configuration
configuration_git_private_key_file: ~/.ssh/id_rsa.configuration
configuration_type: git

configuration_git_host: {{cookiecutter.git_host}}
configuration_git_port: {{cookiecutter.git_port}}
# yamllint disable rule:line-length
configuration_git_public_key: FIXME
# yamllint enable rule:line-length
configuration_git_protocol: ssh
configuration_git_repository: {{cookiecutter.git_repository}}
configuration_git_username: {{cookiecutter.git_username}}
configuration_git_version: {{cookiecutter.git_version}}
